# Copyright NIT Warangal Academic Records Blockchain Network
# Docker Compose configuration for the complete network

version: '3.7'

volumes:
  orderer.nitw.edu:
  peer0.nitwarangal.nitw.edu:
  peer1.nitwarangal.nitw.edu:
  peer0.departments.nitw.edu:
  peer1.departments.nitw.edu:
  peer0.verifiers.nitw.edu:

networks:
  nitw:
    name: fabric_nitw

services:
  orderer.nitw.edu:
    container_name: orderer.nitw.edu
    image: hyperledger/fabric-orderer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.nitw.edu:9443
      - ORDERER_METRICS_PROVIDER=prometheus
    working_dir: /root
    command: orderer
    volumes:
      - ../organizations/ordererOrganizations/nitw.edu/orderers/orderer.nitw.edu/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/nitw.edu/orderers/orderer.nitw.edu/tls:/var/hyperledger/orderer/tls
      - orderer.nitw.edu:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - nitw

  peer0.nitwarangal.nitw.edu:
    container_name: peer0.nitwarangal.nitw.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.nitwarangal.nitw.edu
      - CORE_PEER_ADDRESS=peer0.nitwarangal.nitw.edu:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nitwarangal.nitw.edu:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nitwarangal.nitw.edu:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nitwarangal.nitw.edu:7051
      - CORE_PEER_LOCALMSPID=NITWarangalMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_nitw
      - CORE_OPERATIONS_LISTENADDRESS=peer0.nitwarangal.nitw.edu:9446
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0nitwarangal"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../organizations/peerOrganizations/nitwarangal.nitw.edu/peers/peer0.nitwarangal.nitw.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/nitwarangal.nitw.edu/peers/peer0.nitwarangal.nitw.edu/tls:/etc/hyperledger/fabric/tls
      - peer0.nitwarangal.nitw.edu:/var/hyperledger/production
    ports:
      - 7051:7051
      - 9446:9446
    networks:
      - nitw

  peer1.nitwarangal.nitw.edu:
    container_name: peer1.nitwarangal.nitw.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer1.nitwarangal.nitw.edu
      - CORE_PEER_ADDRESS=peer1.nitwarangal.nitw.edu:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.nitwarangal.nitw.edu:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nitwarangal.nitw.edu:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nitwarangal.nitw.edu:8051
      - CORE_PEER_LOCALMSPID=NITWarangalMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_nitw
      - CORE_OPERATIONS_LISTENADDRESS=peer1.nitwarangal.nitw.edu:9447
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1nitwarangal"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../organizations/peerOrganizations/nitwarangal.nitw.edu/peers/peer1.nitwarangal.nitw.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/nitwarangal.nitw.edu/peers/peer1.nitwarangal.nitw.edu/tls:/etc/hyperledger/fabric/tls
      - peer1.nitwarangal.nitw.edu:/var/hyperledger/production
    ports:
      - 8051:8051
      - 9447:9447
    networks:
      - nitw

  peer0.departments.nitw.edu:
    container_name: peer0.departments.nitw.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.departments.nitw.edu
      - CORE_PEER_ADDRESS=peer0.departments.nitw.edu:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.departments.nitw.edu:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.departments.nitw.edu:10051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.departments.nitw.edu:9051
      - CORE_PEER_LOCALMSPID=DepartmentsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_nitw
      - CORE_OPERATIONS_LISTENADDRESS=peer0.departments.nitw.edu:9448
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0departments"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../organizations/peerOrganizations/departments.nitw.edu/peers/peer0.departments.nitw.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/departments.nitw.edu/peers/peer0.departments.nitw.edu/tls:/etc/hyperledger/fabric/tls
      - peer0.departments.nitw.edu:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9448:9448
    networks:
      - nitw

  peer1.departments.nitw.edu:
    container_name: peer1.departments.nitw.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer1.departments.nitw.edu
      - CORE_PEER_ADDRESS=peer1.departments.nitw.edu:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.departments.nitw.edu:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.departments.nitw.edu:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.departments.nitw.edu:10051
      - CORE_PEER_LOCALMSPID=DepartmentsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_nitw
      - CORE_OPERATIONS_LISTENADDRESS=peer1.departments.nitw.edu:9449
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1departments"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../organizations/peerOrganizations/departments.nitw.edu/peers/peer1.departments.nitw.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/departments.nitw.edu/peers/peer1.departments.nitw.edu/tls:/etc/hyperledger/fabric/tls
      - peer1.departments.nitw.edu:/var/hyperledger/production
    ports:
      - 10051:10051
      - 9449:9449
    networks:
      - nitw

  peer0.verifiers.nitw.edu:
    container_name: peer0.verifiers.nitw.edu
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.verifiers.nitw.edu
      - CORE_PEER_ADDRESS=peer0.verifiers.nitw.edu:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.verifiers.nitw.edu:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.verifiers.nitw.edu:11051
      - CORE_PEER_LOCALMSPID=VerifiersMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_nitw
      - CORE_OPERATIONS_LISTENADDRESS=peer0.verifiers.nitw.edu:9450
      - CORE_METRICS_PROVIDER=prometheus
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0verifiers"}
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
    working_dir: /root
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ../../config/core.yaml:/etc/hyperledger/fabric/core.yaml
      - ../organizations/peerOrganizations/verifiers.nitw.edu/peers/peer0.verifiers.nitw.edu/msp:/etc/hyperledger/fabric/msp
      - ../organizations/peerOrganizations/verifiers.nitw.edu/peers/peer0.verifiers.nitw.edu/tls:/etc/hyperledger/fabric/tls
      - peer0.verifiers.nitw.edu:/var/hyperledger/production
    ports:
      - 11051:11051
      - 9450:9450
    networks:
      - nitw

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
      - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
    depends_on:
      - peer0.nitwarangal.nitw.edu
      - peer1.nitwarangal.nitw.edu
      - peer0.departments.nitw.edu
      - peer1.departments.nitw.edu
      - peer0.verifiers.nitw.edu
    networks:
      - nitw
